name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
     - uses: docker/login-action@v3
       with:
        registry: stefan.pase.dev
        username: ${{ secrets.HARBOR_USERNAME  }}
        password: ${{ secrets.HARBOR_PASSWORD }}
     - uses: actions/checkout@v3
     - name: Run Prisma Cloud 
       id: prisma-cloud
       uses: bridgecrewio/checkov-action@master
       env:
        PRISMA_API_URL: https://api.eu.prismacloud.io
       with:
        api-key: ${{ secrets.BC_API_KEY }}
        soft_fail: true
     - name: Build the Docker image
       run: |
         docker build . --file Dockerfile --tag stefan.pase.dev/demoaction/my-image-name:${{ github.run_number }}
         docker push stefan.pase.dev/demoaction/my-image-name:${{ github.run_number }}
